// [TODO] Code generated by "github.com/magicsong/generate-go-for-sonarqube", you should edit some validation logic here

package sonarqube

import "github.com/magicsong/generate-go-for-sonarqube/pkg/validation"

func (s *AuthenticationService) ValidateLoginOpt(opt *AuthenticationLoginOption) *valiation.Error {
	return nil
}
func (s *CeService) ValidateActivityOpt(opt *CeActivityOption) *valiation.Error {
	return nil
}
func (s *CeService) ValidateComponentOpt(opt *CeComponentOption) *valiation.Error {
	return nil
}
func (s *CeService) ValidateTaskOpt(opt *CeTaskOption) *valiation.Error {
	return nil
}
func (s *ComponentsService) ValidateSearchOpt(opt *ComponentsSearchOption) *valiation.Error {
	return nil
}
func (s *ComponentsService) ValidateShowOpt(opt *ComponentsShowOption) *valiation.Error {
	return nil
}
func (s *ComponentsService) ValidateTreeOpt(opt *ComponentsTreeOption) *valiation.Error {
	return nil
}
func (s *Custom_measuresService) ValidateCreateOpt(opt *CustomMeasuresCreateOption) *valiation.Error {
	return nil
}
func (s *Custom_measuresService) ValidateDeleteOpt(opt *CustomMeasuresDeleteOption) *valiation.Error {
	return nil
}
func (s *Custom_measuresService) ValidateSearchOpt(opt *CustomMeasuresSearchOption) *valiation.Error {
	return nil
}
func (s *Custom_measuresService) ValidateUpdateOpt(opt *CustomMeasuresUpdateOption) *valiation.Error {
	return nil
}
func (s *DuplicationsService) ValidateShowOpt(opt *DuplicationsShowOption) *valiation.Error {
	return nil
}
func (s *EditionsService) ValidateApplyLicenseOpt(opt *EditionsApplyLicenseOption) *valiation.Error {
	return nil
}
func (s *EditionsService) ValidatePreviewOpt(opt *EditionsPreviewOption) *valiation.Error {
	return nil
}
func (s *FavoritesService) ValidateAddOpt(opt *FavoritesAddOption) *valiation.Error {
	return nil
}
func (s *FavoritesService) ValidateRemoveOpt(opt *FavoritesRemoveOption) *valiation.Error {
	return nil
}
func (s *FavoritesService) ValidateSearchOpt(opt *FavoritesSearchOption) *valiation.Error {
	return nil
}
func (s *IssuesService) ValidateAddCommentOpt(opt *IssuesAddCommentOption) *valiation.Error {
	return nil
}
func (s *IssuesService) ValidateAssignOpt(opt *IssuesAssignOption) *valiation.Error {
	return nil
}
func (s *IssuesService) ValidateAuthorsOpt(opt *IssuesAuthorsOption) *valiation.Error {
	return nil
}
func (s *IssuesService) ValidateBulkChangeOpt(opt *IssuesBulkChangeOption) *valiation.Error {
	return nil
}
func (s *IssuesService) ValidateChangelogOpt(opt *IssuesChangelogOption) *valiation.Error {
	return nil
}
func (s *IssuesService) ValidateDeleteCommentOpt(opt *IssuesDeleteCommentOption) *valiation.Error {
	return nil
}
func (s *IssuesService) ValidateDoTransitionOpt(opt *IssuesDoTransitionOption) *valiation.Error {
	return nil
}
func (s *IssuesService) ValidateEditCommentOpt(opt *IssuesEditCommentOption) *valiation.Error {
	return nil
}
func (s *IssuesService) ValidateSearchOpt(opt *IssuesSearchOption) *valiation.Error {
	return nil
}
func (s *IssuesService) ValidateSetSeverityOpt(opt *IssuesSetSeverityOption) *valiation.Error {
	return nil
}
func (s *IssuesService) ValidateSetTagsOpt(opt *IssuesSetTagsOption) *valiation.Error {
	return nil
}
func (s *IssuesService) ValidateSetTypeOpt(opt *IssuesSetTypeOption) *valiation.Error {
	return nil
}
func (s *IssuesService) ValidateTagsOpt(opt *IssuesTagsOption) *valiation.Error {
	return nil
}
func (s *LanguagesService) ValidateListOpt(opt *LanguagesListOption) *valiation.Error {
	return nil
}
func (s *MeasuresService) ValidateComponentOpt(opt *MeasuresComponentOption) *valiation.Error {
	return nil
}
func (s *MeasuresService) ValidateComponentTreeOpt(opt *MeasuresComponentTreeOption) *valiation.Error {
	return nil
}
func (s *MeasuresService) ValidateSearchHistoryOpt(opt *MeasuresSearchHistoryOption) *valiation.Error {
	return nil
}
func (s *MetricsService) ValidateCreateOpt(opt *MetricsCreateOption) *valiation.Error {
	return nil
}
func (s *MetricsService) ValidateDeleteOpt(opt *MetricsDeleteOption) *valiation.Error {
	return nil
}
func (s *MetricsService) ValidateSearchOpt(opt *MetricsSearchOption) *valiation.Error {
	return nil
}
func (s *MetricsService) ValidateUpdateOpt(opt *MetricsUpdateOption) *valiation.Error {
	return nil
}
func (s *NotificationsService) ValidateAddOpt(opt *NotificationsAddOption) *valiation.Error {
	return nil
}
func (s *NotificationsService) ValidateListOpt(opt *NotificationsListOption) *valiation.Error {
	return nil
}
func (s *NotificationsService) ValidateRemoveOpt(opt *NotificationsRemoveOption) *valiation.Error {
	return nil
}
func (s *PermissionsService) ValidateAddGroupOpt(opt *PermissionsAddGroupOption) *valiation.Error {
	return nil
}
func (s *PermissionsService) ValidateAddGroupToTemplateOpt(opt *PermissionsAddGroupToTemplateOption) *valiation.Error {
	return nil
}
func (s *PermissionsService) ValidateAddProjectCreatorToTemplateOpt(opt *PermissionsAddProjectCreatorToTemplateOption) *valiation.Error {
	return nil
}
func (s *PermissionsService) ValidateAddUserOpt(opt *PermissionsAddUserOption) *valiation.Error {
	return nil
}
func (s *PermissionsService) ValidateAddUserToTemplateOpt(opt *PermissionsAddUserToTemplateOption) *valiation.Error {
	return nil
}
func (s *PermissionsService) ValidateApplyTemplateOpt(opt *PermissionsApplyTemplateOption) *valiation.Error {
	return nil
}
func (s *PermissionsService) ValidateBulkApplyTemplateOpt(opt *PermissionsBulkApplyTemplateOption) *valiation.Error {
	return nil
}
func (s *PermissionsService) ValidateCreateTemplateOpt(opt *PermissionsCreateTemplateOption) *valiation.Error {
	return nil
}
func (s *PermissionsService) ValidateDeleteTemplateOpt(opt *PermissionsDeleteTemplateOption) *valiation.Error {
	return nil
}
func (s *PermissionsService) ValidateRemoveGroupOpt(opt *PermissionsRemoveGroupOption) *valiation.Error {
	return nil
}
func (s *PermissionsService) ValidateRemoveGroupFromTemplateOpt(opt *PermissionsRemoveGroupFromTemplateOption) *valiation.Error {
	return nil
}
func (s *PermissionsService) ValidateRemoveProjectCreatorFromTemplateOpt(opt *PermissionsRemoveProjectCreatorFromTemplateOption) *valiation.Error {
	return nil
}
func (s *PermissionsService) ValidateRemoveUserOpt(opt *PermissionsRemoveUserOption) *valiation.Error {
	return nil
}
func (s *PermissionsService) ValidateRemoveUserFromTemplateOpt(opt *PermissionsRemoveUserFromTemplateOption) *valiation.Error {
	return nil
}
func (s *PermissionsService) ValidateSearchProjectPermissionsOpt(opt *PermissionsSearchProjectPermissionsOption) *valiation.Error {
	return nil
}
func (s *PermissionsService) ValidateSearchTemplatesOpt(opt *PermissionsSearchTemplatesOption) *valiation.Error {
	return nil
}
func (s *PermissionsService) ValidateSetDefaultTemplateOpt(opt *PermissionsSetDefaultTemplateOption) *valiation.Error {
	return nil
}
func (s *PermissionsService) ValidateUpdateTemplateOpt(opt *PermissionsUpdateTemplateOption) *valiation.Error {
	return nil
}
func (s *PluginsService) ValidateInstallOpt(opt *PluginsInstallOption) *valiation.Error {
	return nil
}
func (s *PluginsService) ValidateInstalledOpt(opt *PluginsInstalledOption) *valiation.Error {
	return nil
}
func (s *PluginsService) ValidateUninstallOpt(opt *PluginsUninstallOption) *valiation.Error {
	return nil
}
func (s *PluginsService) ValidateUpdateOpt(opt *PluginsUpdateOption) *valiation.Error {
	return nil
}
func (s *Project_analysesService) ValidateCreateEventOpt(opt *ProjectAnalysesCreateEventOption) *valiation.Error {
	return nil
}
func (s *Project_analysesService) ValidateDeleteOpt(opt *ProjectAnalysesDeleteOption) *valiation.Error {
	return nil
}
func (s *Project_analysesService) ValidateDeleteEventOpt(opt *ProjectAnalysesDeleteEventOption) *valiation.Error {
	return nil
}
func (s *Project_analysesService) ValidateSearchOpt(opt *ProjectAnalysesSearchOption) *valiation.Error {
	return nil
}
func (s *Project_analysesService) ValidateUpdateEventOpt(opt *ProjectAnalysesUpdateEventOption) *valiation.Error {
	return nil
}
func (s *Project_badgesService) ValidateMeasureOpt(opt *ProjectBadgesMeasureOption) *valiation.Error {
	return nil
}
func (s *Project_badgesService) ValidateQualityGateOpt(opt *ProjectBadgesQualityGateOption) *valiation.Error {
	return nil
}
func (s *Project_branchesService) ValidateDeleteOpt(opt *ProjectBranchesDeleteOption) *valiation.Error {
	return nil
}
func (s *Project_branchesService) ValidateListOpt(opt *ProjectBranchesListOption) *valiation.Error {
	return nil
}
func (s *Project_branchesService) ValidateRenameOpt(opt *ProjectBranchesRenameOption) *valiation.Error {
	return nil
}
func (s *Project_linksService) ValidateCreateOpt(opt *ProjectLinksCreateOption) *valiation.Error {
	return nil
}
func (s *Project_linksService) ValidateDeleteOpt(opt *ProjectLinksDeleteOption) *valiation.Error {
	return nil
}
func (s *Project_linksService) ValidateSearchOpt(opt *ProjectLinksSearchOption) *valiation.Error {
	return nil
}
func (s *Project_pull_requestsService) ValidateDeleteOpt(opt *ProjectPullRequestsDeleteOption) *valiation.Error {
	return nil
}
func (s *Project_pull_requestsService) ValidateListOpt(opt *ProjectPullRequestsListOption) *valiation.Error {
	return nil
}
func (s *Project_tagsService) ValidateSearchOpt(opt *ProjectTagsSearchOption) *valiation.Error {
	return nil
}
func (s *Project_tagsService) ValidateSetOpt(opt *ProjectTagsSetOption) *valiation.Error {
	return nil
}
func (s *ProjectsService) ValidateBulkDeleteOpt(opt *ProjectsBulkDeleteOption) *valiation.Error {
	return nil
}
func (s *ProjectsService) ValidateBulkUpdateKeyOpt(opt *ProjectsBulkUpdateKeyOption) *valiation.Error {
	return nil
}
func (s *ProjectsService) ValidateCreateOpt(opt *ProjectsCreateOption) *valiation.Error {
	return nil
}
func (s *ProjectsService) ValidateDeleteOpt(opt *ProjectsDeleteOption) *valiation.Error {
	return nil
}
func (s *ProjectsService) ValidateGhostsOpt(opt *ProjectsGhostsOption) *valiation.Error {
	return nil
}
func (s *ProjectsService) ValidateIndexOpt(opt *ProjectsIndexOption) *valiation.Error {
	return nil
}
func (s *ProjectsService) ValidateProvisionedOpt(opt *ProjectsProvisionedOption) *valiation.Error {
	return nil
}
func (s *ProjectsService) ValidateSearchOpt(opt *ProjectsSearchOption) *valiation.Error {
	return nil
}
func (s *ProjectsService) ValidateUpdateKeyOpt(opt *ProjectsUpdateKeyOption) *valiation.Error {
	return nil
}
func (s *ProjectsService) ValidateUpdateVisibilityOpt(opt *ProjectsUpdateVisibilityOption) *valiation.Error {
	return nil
}
func (s *QualitygatesService) ValidateCopyOpt(opt *QualitygatesCopyOption) *valiation.Error {
	return nil
}
func (s *QualitygatesService) ValidateCreateOpt(opt *QualitygatesCreateOption) *valiation.Error {
	return nil
}
func (s *QualitygatesService) ValidateCreateConditionOpt(opt *QualitygatesCreateConditionOption) *valiation.Error {
	return nil
}
func (s *QualitygatesService) ValidateDeleteConditionOpt(opt *QualitygatesDeleteConditionOption) *valiation.Error {
	return nil
}
func (s *QualitygatesService) ValidateDeselectOpt(opt *QualitygatesDeselectOption) *valiation.Error {
	return nil
}
func (s *QualitygatesService) ValidateDestroyOpt(opt *QualitygatesDestroyOption) *valiation.Error {
	return nil
}
func (s *QualitygatesService) ValidateGetByProjectOpt(opt *QualitygatesGetByProjectOption) *valiation.Error {
	return nil
}
func (s *QualitygatesService) ValidateListOpt(opt *QualitygatesListOption) *valiation.Error {
	return nil
}
func (s *QualitygatesService) ValidateProjectStatusOpt(opt *QualitygatesProjectStatusOption) *valiation.Error {
	return nil
}
func (s *QualitygatesService) ValidateRenameOpt(opt *QualitygatesRenameOption) *valiation.Error {
	return nil
}
func (s *QualitygatesService) ValidateSearchOpt(opt *QualitygatesSearchOption) *valiation.Error {
	return nil
}
func (s *QualitygatesService) ValidateSelectOpt(opt *QualitygatesSelectOption) *valiation.Error {
	return nil
}
func (s *QualitygatesService) ValidateSetAsDefaultOpt(opt *QualitygatesSetAsDefaultOption) *valiation.Error {
	return nil
}
func (s *QualitygatesService) ValidateShowOpt(opt *QualitygatesShowOption) *valiation.Error {
	return nil
}
func (s *QualitygatesService) ValidateUpdateConditionOpt(opt *QualitygatesUpdateConditionOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateActivateRuleOpt(opt *QualityprofilesActivateRuleOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateActivateRulesOpt(opt *QualityprofilesActivateRulesOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateAddProjectOpt(opt *QualityprofilesAddProjectOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateBackupOpt(opt *QualityprofilesBackupOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateChangeParentOpt(opt *QualityprofilesChangeParentOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateChangelogOpt(opt *QualityprofilesChangelogOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateCopyOpt(opt *QualityprofilesCopyOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateCreateOpt(opt *QualityprofilesCreateOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateDeactivateRuleOpt(opt *QualityprofilesDeactivateRuleOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateDeactivateRulesOpt(opt *QualityprofilesDeactivateRulesOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateDeleteOpt(opt *QualityprofilesDeleteOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateExportOpt(opt *QualityprofilesExportOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateInheritanceOpt(opt *QualityprofilesInheritanceOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateProjectsOpt(opt *QualityprofilesProjectsOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateRemoveProjectOpt(opt *QualityprofilesRemoveProjectOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateRenameOpt(opt *QualityprofilesRenameOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateRestoreOpt(opt *QualityprofilesRestoreOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateSearchOpt(opt *QualityprofilesSearchOption) *valiation.Error {
	return nil
}
func (s *QualityprofilesService) ValidateSetDefaultOpt(opt *QualityprofilesSetDefaultOption) *valiation.Error {
	return nil
}
func (s *RulesService) ValidateCreateOpt(opt *RulesCreateOption) *valiation.Error {
	return nil
}
func (s *RulesService) ValidateDeleteOpt(opt *RulesDeleteOption) *valiation.Error {
	return nil
}
func (s *RulesService) ValidateRepositoriesOpt(opt *RulesRepositoriesOption) *valiation.Error {
	return nil
}
func (s *RulesService) ValidateSearchOpt(opt *RulesSearchOption) *valiation.Error {
	return nil
}
func (s *RulesService) ValidateShowOpt(opt *RulesShowOption) *valiation.Error {
	return nil
}
func (s *RulesService) ValidateTagsOpt(opt *RulesTagsOption) *valiation.Error {
	return nil
}
func (s *RulesService) ValidateUpdateOpt(opt *RulesUpdateOption) *valiation.Error {
	return nil
}
func (s *SettingsService) ValidateListDefinitionsOpt(opt *SettingsListDefinitionsOption) *valiation.Error {
	return nil
}
func (s *SettingsService) ValidateResetOpt(opt *SettingsResetOption) *valiation.Error {
	return nil
}
func (s *SettingsService) ValidateSetOpt(opt *SettingsSetOption) *valiation.Error {
	return nil
}
func (s *SettingsService) ValidateValuesOpt(opt *SettingsValuesOption) *valiation.Error {
	return nil
}
func (s *SourcesService) ValidateRawOpt(opt *SourcesRawOption) *valiation.Error {
	return nil
}
func (s *SourcesService) ValidateScmOpt(opt *SourcesScmOption) *valiation.Error {
	return nil
}
func (s *SourcesService) ValidateShowOpt(opt *SourcesShowOption) *valiation.Error {
	return nil
}
func (s *SystemService) ValidateChangeLogLevelOpt(opt *SystemChangeLogLevelOption) *valiation.Error {
	return nil
}
func (s *SystemService) ValidateLogsOpt(opt *SystemLogsOption) *valiation.Error {
	return nil
}
func (s *User_groupsService) ValidateAddUserOpt(opt *UserGroupsAddUserOption) *valiation.Error {
	return nil
}
func (s *User_groupsService) ValidateCreateOpt(opt *UserGroupsCreateOption) *valiation.Error {
	return nil
}
func (s *User_groupsService) ValidateDeleteOpt(opt *UserGroupsDeleteOption) *valiation.Error {
	return nil
}
func (s *User_groupsService) ValidateRemoveUserOpt(opt *UserGroupsRemoveUserOption) *valiation.Error {
	return nil
}
func (s *User_groupsService) ValidateSearchOpt(opt *UserGroupsSearchOption) *valiation.Error {
	return nil
}
func (s *User_groupsService) ValidateUpdateOpt(opt *UserGroupsUpdateOption) *valiation.Error {
	return nil
}
func (s *User_groupsService) ValidateUsersOpt(opt *UserGroupsUsersOption) *valiation.Error {
	return nil
}
func (s *User_tokensService) ValidateGenerateOpt(opt *UserTokensGenerateOption) *valiation.Error {
	return nil
}
func (s *User_tokensService) ValidateRevokeOpt(opt *UserTokensRevokeOption) *valiation.Error {
	return nil
}
func (s *User_tokensService) ValidateSearchOpt(opt *UserTokensSearchOption) *valiation.Error {
	return nil
}
func (s *UsersService) ValidateChangePasswordOpt(opt *UsersChangePasswordOption) *valiation.Error {
	return nil
}
func (s *UsersService) ValidateCreateOpt(opt *UsersCreateOption) *valiation.Error {
	return nil
}
func (s *UsersService) ValidateDeactivateOpt(opt *UsersDeactivateOption) *valiation.Error {
	return nil
}
func (s *UsersService) ValidateGroupsOpt(opt *UsersGroupsOption) *valiation.Error {
	return nil
}
func (s *UsersService) ValidateSearchOpt(opt *UsersSearchOption) *valiation.Error {
	return nil
}
func (s *UsersService) ValidateUpdateOpt(opt *UsersUpdateOption) *valiation.Error {
	return nil
}
func (s *WebhooksService) ValidateCreateOpt(opt *WebhooksCreateOption) *valiation.Error {
	return nil
}
func (s *WebhooksService) ValidateDeleteOpt(opt *WebhooksDeleteOption) *valiation.Error {
	return nil
}
func (s *WebhooksService) ValidateDeliveriesOpt(opt *WebhooksDeliveriesOption) *valiation.Error {
	return nil
}
func (s *WebhooksService) ValidateDeliveryOpt(opt *WebhooksDeliveryOption) *valiation.Error {
	return nil
}
func (s *WebhooksService) ValidateListOpt(opt *WebhooksListOption) *valiation.Error {
	return nil
}
func (s *WebhooksService) ValidateUpdateOpt(opt *WebhooksUpdateOption) *valiation.Error {
	return nil
}
func (s *WebservicesService) ValidateListOpt(opt *WebservicesListOption) *valiation.Error {
	return nil
}
func (s *WebservicesService) ValidateResponseExampleOpt(opt *WebservicesResponseExampleOption) *valiation.Error {
	return nil
}
